---
# vars file for zkvm-compute

# ansible temp path
ansible_temp_path: "/tmp/ansible/"

# config file path on controller
controller_nova_conf_path: "/etc/kolla/nova-api/nova.conf"
controller_neutron_conf_path: "/etc/kolla/neutron-server/neutron.conf"
controller_neutron_ml2_conf_path: "/etc/kolla/neutron-openvswitch-agent/ml2_conf.ini"

config_files:
  nova_conf:
    src: "{{ controller_nova_conf_path }}"
    dest: /etc/nova/nova.conf
    fn: nova.conf
  neutron_conf:
    src: "{{ controller_neutron_conf_path }}"
    dest: /etc/neutron/neutron.conf
    fn: neutron.conf
  neutron_ml2_ini:
    src: "{{ controller_neutron_ml2_conf_path }}"
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    fn: openvswitch_agent.ini

# network devices list. e.g. OSA list.
#lpar_net_dev_list:
#  - "2000-2002"

lpar_net_dev_list: '[]'

#=========================
# local repository options
#=========================

# set as true will setup software repositories
enable_local_repo: "true"

# repo type, currently only support nfs
repo_type: "nfs"

# iso files that to be mount as software repositories
iso_files:
  sles12sp3-sdk1: "/var/lib/nova/ce-files/isos/SLE-12-SP3-SDK-DVD-s390x-GM-DVD1.iso"
  sles12sp3-dvd1: "/var/lib/nova/ce-files/isos/SLE-12-SP3-Server-DVD-s390x-GM-DVD1.iso"

# software repositories that in local file system
repo_dir:
  openstack-ocata: "/var/lib/nova/ce-files/Ocata/SLE_12_SP3"

